// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATDErLVL4PXMFRAB53aOypro6K2MJ1KWQ',
    appId: '1:428302826554:web:b64065ae58469248a44903',
    messagingSenderId: '428302826554',
    projectId: 'motojo-fbd36',
    authDomain: 'motojo-fbd36.firebaseapp.com',
    storageBucket: 'motojo-fbd36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0LGIxZEyzIQTirv3X_rZ2Vz2zumVj6E',
    appId: '1:428302826554:android:674b0c686dc5452ca44903',
    messagingSenderId: '428302826554',
    projectId: 'motojo-fbd36',
    storageBucket: 'motojo-fbd36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6IMW0k7ZnGh_HXcfCekT27HwJuxBeoTY',
    appId: '1:428302826554:ios:1b170f31af4bce07a44903',
    messagingSenderId: '428302826554',
    projectId: 'motojo-fbd36',
    storageBucket: 'motojo-fbd36.appspot.com',
    iosBundleId: 'com.example.motojo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6IMW0k7ZnGh_HXcfCekT27HwJuxBeoTY',
    appId: '1:428302826554:ios:8bc321ba7d41f9a5a44903',
    messagingSenderId: '428302826554',
    projectId: 'motojo-fbd36',
    storageBucket: 'motojo-fbd36.appspot.com',
    iosBundleId: 'com.example.motojo.RunnerTests',
  );
}
